### ISSUE TITLE
ObservableWeakSet fails  during npm install with typescript 2.5

### ISSUE THREAD

**Issue by davutg** [Narazaka/observable-collection.js#2]
The very [similar ](https://github.com/Romakita/ts-express-decorators/issues/45)issue occurs during build 

**ERROR in node_modules/observable-collection/dist/es2015/ObservableWeakSet.d.ts(4,59): error TS2344: Type 'T' does not satisfy the constraint 'object**

https://github.com/Romakita/ts-express-decorators/issues/45

**Comment by Narazaka** [comment]
thank you for reporting.

**Comment by Narazaka** [comment]
fixed on v1.2.3
